import { PerformanceDataType } from "@/types/api-types";

export const NINEWATT_PERFORMANCE_LIST: PerformanceDataType[] = [
  {
    id: 1,
    type: "R&D",
    category: "efficiency_diagnosis",
    period: "2019.07.01~2021.06.30",
    agency: "중소기업기술정보진흥원",
    title: "TIPS, 민간투자주도형 기술창업지원 (빅데이터 분석기반 건물에너지 절감 AI 플랫폼)",
    operatingOrganization: "주식회사 블루포인트파트너스",
  },
  {
    id: 2,
    type: "R&D",
    category: "efficiency_diagnosis",
    period: "-",
    agency: "한국전기산업진흥회",
    title:
      "기업자율형 상생프로그램 육성기업 한국전력공사 에너지 스타트업 프로그램-에너지 소비패턴 분석 및 에너지 절감 교육을 통한 에너지 절감 AI 플랫폼",
    operatingOrganization: "한국전기산업진흥회",
  },
  {
    id: 3,
    type: "사업화",
    category: "global",
    period: "2019.10.07~2019.12.31",
    agency: "(재)인천테크노파크",
    title: "2019년 SW융합 맞춤형 글로벌 지원사업",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 4,
    type: "사업화",
    category: "global",
    period: "2019.08.01~2020.07.31",
    agency: "중소벤처기업부",
    title: "2019년 TIPS 해외마케팅 지원사업 민관공동 창업자 발굴육성사업",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 5,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2019.11.18~2020.09.18",
    agency: "(재)한국사회투자",
    title:
      "2019년도 한전 에너지분야 사회적경제조직 임팩트투자 에너지 소비패턴 및 사용량 분석기(Edge Computing Controller; ECC) 및 솔루션 개발, 생산 및 판매",
    operatingOrganization: "(재)한국사회투자",
  },
  {
    id: 6,
    type: "사업화",
    category: "etc",
    period: "2019.11.11~2019.12.31",
    agency: "(재)인천테크노파크",
    title: "SW융합클러스터 2.0 데이터 기반 BM연구회 지원사업",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 7,
    type: "사업화",
    category: "global",
    period: "2019.12.10~2020.06.30",
    agency: "(재)인천테크노파크",
    title:
      "SW융합클러스터 2.0 글로벌 산학연 협력사업 독거노인의 디지털정보 접근성 향상을 고려한 디바이스 개발",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 8,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2020.04.13~2020.11.20",
    agency: "한국에너지공단",
    title: "기업협력군 에너지 동행 사업",
    operatingOrganization: "한국전력공사",
  },
  {
    id: 9,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2020.05.01~2020.12.31",
    agency: "(재)인천테크노파크",
    title: "SW융합클러스터 2.0사업 (에너지바우처 연계형 고독사 사전예방 SW개발)",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 10,
    type: "지원사업",
    category: "etc",
    period: "2020.02.08~2020.12.31",
    agency: "한국사회적기업진흥원",
    title: "사회적기업가 육성사업",
    operatingOrganization: "에스이임파워 사회적협동조합",
  },
  {
    id: 11,
    type: "지원사업",
    category: "efficiency_diagnosis",
    period: "2020.04.13~2020.08.12",
    agency: "(재)인천테크노파크",
    title:
      "2020년도 연구개발 기획 컨설팅 지원사업 (에너지바우처 연계형 적정 에너지소비 권장서비스)",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 12,
    type: "지원사업",
    category: "etc",
    period: "2020.08.01~2021.04.30",
    agency: "한국전기산업진흥회장",
    title:
      "상생서포터즈 프로그램 육성기업 표준협약 (기업자율형 상생프로그램 한전 KDN 에너지 ICT4.0스타트업 육성사업)",
    operatingOrganization: "한국전기산업진흥회장",
  },
  {
    id: 13,
    type: "지원사업",
    category: "etc",
    period: "2020.10.05~2021.06.30",
    agency: "한국전기산업진흥회장",
    title:
      "기업자율형 상생프로그램 육성기업 표준협약(기업자율형 상생프로그램 KEPCO 에너지스타트업 지원사업)",
    operatingOrganization: "한국전기산업진흥회장",
  },
  {
    id: 14,
    type: "R&D",
    category: "urban_carbon",
    period: "2021.01.01~2023.12.31",
    agency: "과학기술정보통신부",
    title:
      "인공지능 중심 산업융합 집적단지 조성(R&D)(AI기반의 사전예방 및 빠른 복구가 가능한 에너지 재난대응 플랫폼 개발)",
    operatingOrganization: "서울대학교 산학협력단",
  },
  {
    id: 15,
    type: "R&D",
    category: "energy_business",
    period: "2021.04.01~2025.12.31",
    agency: "한국에너지기술평가원",
    title: "경북지역 풍력에너지 클러스터 인재양성사업 (R&D)",
    operatingOrganization: "(재)경북테크노파크",
  },
  {
    id: 16,
    type: "R&D",
    category: "urban_carbon",
    period: "2021.05.01~2021.12.31",
    agency: "과학기술정보통신부",
    title:
      "2021년 핵심산업 클라우드 플래그십 프로젝트 지원과제 (SaaS전환)클라우드 기반 에너지 진단솔루션",
    operatingOrganization: "정보통신산업진흥원",
  },
  {
    id: 17,
    type: "용역",
    category: "zero_energy",
    period: "2021.10.06~2021.12.15",
    agency: "한국건설기술연구원",
    title: "공공건축물 에너지소비량 공개 및 성능개선 사업 제도 기술 지원 용역",
    operatingOrganization: "한국건설기술연구원",
  },
  {
    id: 18,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2021.04.26~2021.11.19",
    agency: "한국에너지공단",
    title: "기업협력군 에너지 동행 사업",
    operatingOrganization: "한국전력공사",
  },
  {
    id: 19,
    type: "사업화",
    category: "etc",
    period: "2021.06.01~2021.10.31",
    agency: "한국데이터산업진흥원",
    title: "2021 DATA-SATARS(데이터 활용 사업화 지원)사업 에너지 투자연계 AI 플랫폼",
    operatingOrganization: "한국데이터산업진흥원",
  },
  {
    id: 20,
    type: "지원사업",
    category: "etc",
    period: "2021.02.01~2021.04.30",
    agency: "(재)함께일하는재단",
    title: "한국지역난방공사 에너지 친환경 기업자율형 지원사업 'The minimize'",
    operatingOrganization: "(재)함께일하는재단",
  },
  {
    id: 21,
    type: "지원사업",
    category: "etc",
    period: "2021.04.15~2021.12.31",
    agency: "한전KDN",
    title: "한전 KDN 사회적경제 지원 경영개선 지원사업",
    operatingOrganization: "(사)함께만드는세상",
  },
  {
    id: 22,
    type: "지원사업",
    category: "etc",
    period: "2021.05.10~2021.08.13",
    agency: "(주)엠와이소셜컴퍼니",
    title: "H온드림 스타트업 그라운드",
    operatingOrganization: "(주)엠와이소셜컴퍼니",
  },
  {
    id: 23,
    type: "지원사업",
    category: "etc",
    period: "2021.06.01~2021.11.30",
    agency: "(재)인천테크노파크",
    title: "SW융합클러스터 2.0사업 SaaS기반 물 음용량 데이터 관리 서비스",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 24,
    type: "지원사업",
    category: "etc",
    period: "2021.09.23~2022.04.30",
    agency: "한국전기산업진흥회",
    title: "기업자율형 상생프로그램 육성기업 2021년 한전 KDN-STARS 기업",
    operatingOrganization: "한국전기산업진흥회",
  },
  {
    id: 25,
    type: "R&D",
    category: "urban_carbon",
    period: "2022.04.01~2025.03.31",
    agency: "중소벤처기업부",
    title: "도시의 탄소감축량과 녹색금융을 융합한 그린리모델링 매칭 서비스",
    operatingOrganization: "중소벤처기업부",
  },
  {
    id: 26,
    type: "R&D",
    category: "urban_carbon",
    period: "2022.04.15~2024.12.31",
    agency: "국토교통과학기술진흥원",
    title: "그린리모델링 효율향상을 위한 디지털진단 모듈화 기술",
    operatingOrganization: "국토교통과학기술진흥원",
  },
  {
    id: 27,
    type: "사업화",
    category: "urban_carbon",
    period: "2022.04.01~2025.03.31",
    agency: "중소벤처기업부",
    title: "그린벤처 프로그램 사업화",
    operatingOrganization: "중소벤처기업부",
  },
  {
    id: 28,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2022.04.29~2022.11.30",
    agency: "한국에너지공단",
    title: "2022년 기업협력군 에너지동행 사업",
    operatingOrganization: "한국전력공사",
  },
  {
    id: 29,
    type: "사업화",
    category: "etc",
    period: "2022.12.15~2023.05.31",
    agency: "중소벤처기업부",
    title: "대-스타 해결사 플랫폼 4차산업",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 30,
    type: "사업화",
    category: "etc",
    period: "2022.11.01~2022.12.31",
    agency: "(재)인천테크노파크",
    title: "인천SOS랩 플랫폼화 기반 구축 과제 수행 기업",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 31,
    type: "사업지원",
    category: "etc",
    period: "2022.02.25~2022.11.30",
    agency: "한국국토정보공사",
    title: "기업자율형 상생프로그램 지원협약 제6회 공간정보 활용 창업 아이디어 공모전 사업화 지원",
    operatingOrganization: "대중소 농어업협력재단",
  },
  {
    id: 32,
    type: "사업지원",
    category: "etc",
    period: "2022.05.01~2023.01.31",
    agency: "중소벤처기업부",
    title: "비대면 스타트업 육성사업 창업기업",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 33,
    type: "사업지원",
    category: "etc",
    period: "2022.06.01~2022.11.30",
    agency: "한국데이터산업진흥원",
    title: "2022년 데이터바우처 지원사업",
    operatingOrganization: "한국데이터산업진흥원",
  },
  {
    id: 34,
    type: "사업지원",
    category: "etc",
    period: "2022.06.03~2022.12.15",
    agency: "한국지능정보사회진흥원",
    title: "2022년 공공데이터 기업매칭 지원사업",
    operatingOrganization: "한국지능정보사회진흥원",
  },
  {
    id: 35,
    type: "사업지원",
    category: "etc",
    period: "2022.09.06~2023.02.28",
    agency: "서울산업진흥원",
    title: "서울창업허브 대기업 협력 프로그램 대기업 LS일렉트릭 협력프로그램",
    operatingOrganization: "서울산업진흥원",
  },
  {
    id: 36,
    type: "사업지원",
    category: "urban_carbon",
    period: "2022.12.01~2023.05.31",
    agency: "연구개발특구진흥재단",
    title: "2022년 인천서구강소특구 특화성장패키지",
    operatingOrganization: "연구개발특구진흥재단",
  },
  {
    id: 37,
    type: "사업지원",
    category: "etc",
    period: "2022.12.26~2023.05.31",
    agency: "한국서부발전",
    title: "한국서부발전 상생형 창업-벤처기업 지원사업",
    operatingOrganization: "한국서부발전",
  },
  {
    id: 38,
    type: "사업지원",
    category: "etc",
    period: "2022.12.20~2023.04.30",
    agency: "(사)함꼐만드는세상",
    title: "2022년 한국지역난방공사 상생형 창업-벤처기업 지원사업",
    operatingOrganization: "(사)함꼐만드는세상",
  },
  {
    id: 39,
    type: "PoC",
    category: "global",
    period: "2022.10.26~2023.02.28",
    agency: "서울산업진흥원",
    title: "SBA-KITA 영국 스마트시티 PoC",
    operatingOrganization: "서울산업진흥원",
  },
  {
    id: 40,
    type: "R&D",
    category: "urban_carbon",
    period: "2023.04.01~2026.12.31",
    agency: "국토교통부",
    title: "건물에너지 소비 데이터 통합관리 기반 구축",
    operatingOrganization: "한국건설기술연구원",
  },
  {
    id: 41,
    type: "R&D",
    category: "smart_city",
    period: "2023.12.10~2026.12.09",
    agency: "중소벤처기업부",
    title: "스케일업 팁스 투자연계 (TIPS)",
    operatingOrganization: "(주)나인와트",
  },
  {
    id: 42,
    type: "용역",
    category: "efficiency_diagnosis",
    period: "2023.04.18~2023.08.30",
    agency: "엘에스일렉트릭",
    title: "스마트진단 MVP 3.0 내 Energy Reporting Service 고도화 용역",
    operatingOrganization: "엘에스일렉트릭",
  },
  {
    id: 43,
    type: "용역",
    category: "etc",
    period: "2023.04.19~2023.12.13",
    agency: "한국전력공사",
    title: "디지털 공사비정보 알고리즘 개발",
    operatingOrganization: "한국전력공사",
  },
  {
    id: 44,
    type: "용역",
    category: "efficiency_diagnosis",
    period: "2023.12.01~2024.01.31",
    agency: "에스큐아이소프트(주)",
    title: "2023년 공공건축물 에너지 소비량 데이터 검증-분석",
    operatingOrganization: "에스큐아이소프트(주)",
  },
  {
    id: 45,
    type: "사업화",
    category: "efficiency_diagnosis",
    period: "2023.05.18~2025.12.31",
    agency: "국토안전관리원",
    title: "2023년 공공건축물 그린리모델링 종합사업지원",
    operatingOrganization: "국토안전관리원",
  },
  {
    id: 46,
    type: "사업지원",
    category: "etc",
    period: "2023.01.01~2023.12.31",
    agency: "-",
    title: "2023 기업광고 지원사업",
    operatingOrganization: "-",
  },
  {
    id: 47,
    type: "사업지원",
    category: "smart_city",
    period: "2023.03.23~2023.11.30",
    agency: "(재)인천테크노파크",
    title: "2023 실증 상용화 프로그램",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 48,
    type: "사업지원",
    category: "etc",
    period: "2023.05.09~2023.08.11",
    agency: "(재)인천테크노파크",
    title: "2023 1차 IP 나래 프로그램",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 49,
    type: "사업지원",
    category: "zero_energy",
    period: "2023.04.20~2023.11.30",
    agency: "인천지식재산센터",
    title: "[인천스타트업파크]Smart-X City(인천도시공사)",
    operatingOrganization: "인천지식재산센터",
  },
  {
    id: 50,
    type: "사업지원",
    category: "global",
    period: "2023.04.20~2023.11.24",
    agency: "(재)인천테크노파크",
    title: "[인천스타트업파크] 스케일업 챌린지랩",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 51,
    type: "사업지원",
    category: "efficiency_diagnosis",
    period: "2023.05.01~2024.02.29",
    agency: "(재)인천테크노파크",
    title: "2023년 창업도약 패키지 지원사업(도시단위 에너지효율화 솔루션)",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 52,
    type: "사업지원",
    category: "urban_carbon",
    period: "2023.07.06~2023.12.31",
    agency: "창업진흥원",
    title: "강남구청 실증 지원사업",
    operatingOrganization: "-",
  },
  {
    id: 53,
    type: "사업지원",
    category: "etc",
    period: "2023.07.31~2023.11.30",
    agency: "인천테크노파크",
    title: "2023년 인공지능(AI)비즈니스 모델 연구회",
    operatingOrganization: "인천테크노파크",
  },
  {
    id: 54,
    type: "사업지원",
    category: "zero_energy",
    period: "2023.08.07~2023.11.30",
    agency: "(재)인천테크노파크",
    title: "인천스타트업파크 Smart-X energy [LS일렉트릭] 프로그램",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 55,
    type: "사업지원",
    category: "etc",
    period: "2023.09.01~2023.11.30",
    agency: "(재)인천테크노파크",
    title: "상생형 창업-벤처기업 지원사업 (KEPCO 스타트업 오픈이노베이션 지원사업)",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 56,
    type: "사업지원",
    category: "etc",
    period: "2023.09.01~2023.11.15",
    agency: "한국전력공사",
    title: "지역 간 비즈니스 모델 실증 지원사업",
    operatingOrganization: "한국전력공사",
  },
  {
    id: 57,
    type: "사업지원",
    category: "global",
    period: "2023.09.18~2023.11.30",
    agency: "(재)인천테크노파크",
    title:
      "상생형 창업-벤처기업 지원사업 (2023년 에너지ICT분야 창업-벤처기업 해외판로 개척 지원사업(해외인증 사업)",
    operatingOrganization: "(재)인천테크노파크",
  },
  {
    id: 58,
    type: "사업지원",
    category: "global",
    period: "2023.09.18~2023.11.30",
    agency: "한전KDN",
    title:
      "상생형 창업-벤처기업 지원사업 (2023년 에너지ICT분야 창업-벤처기업 해외판로 개척 지원사업(해외시장 조사)",
    operatingOrganization: "한전KDN",
  },
  {
    id: 59,
    type: "PoC",
    category: "smart_city",
    period: "2023.11.01~2024.07.31",
    agency: "한전KDN",
    title: "미래 모빌리티 허브의 에너지 효율화 관리를 위한 알고리즘 및 시뮬레이션 개발 및 시각화",
    operatingOrganization: "한전KDN",
  },
  {
    id: 60,
    type: "사업지원",
    category: "etc",
    period: "-",
    agency: "현대엔지비(주)",
    title: "2023 2차 기술개발제품 공공기관 실증지원 사업",
    operatingOrganization: "현대엔지비(주)",
  },
  {
    id: 61,
    type: "PoC",
    category: "global",
    period: "2023.06.01~2023.11.30",
    agency: "중소벤처기업부",
    title: "(KSC)데이터 기반 건물에너지 성능진단 및 그린리모델링 솔루션",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 62,
    type: "PoC",
    category: "global",
    period: "2023.12.08~2024.12.13",
    agency: "서울디지털재단",
    title: "서울 스마트도시 솔루션 해외(런던) 실증 지원사업",
    operatingOrganization: "서울디지털재단",
  },
  {
    id: 63,
    type: "R&D",
    category: "urban_carbon",
    period: "2024.07.01~2027.04",
    agency: "국토교통과학기술진흥원",
    title:
      "협력거점형 국토교통 국제협력 연구개발 사업 (도시 건물 넷 제로 혁신적 전환 위한 AI어시스턴트 건물 에너지 분석 기술 및 플랫폼 개발)",
    operatingOrganization: "한국건설기술연구원",
  },
  {
    id: 64,
    type: "지원사업",
    category: "etc",
    period: "2024.03.29~2024.12.31",
    agency: "(주)탭엔젤파트너스",
    title: "2024년 농식품 기술창업 엑셀러레이팅 협약",
    operatingOrganization: "(주)탭엔젤파트너스",
  },
  {
    id: 65,
    type: "지원사업",
    category: "global",
    period: "2024.07.24~2024.11.29",
    agency: "한전KDN",
    title: "2024년 에너지 ICT분야 창업-벤처기업 해외판로 개척 지원사업",
    operatingOrganization: "한전KDN",
  },
  {
    id: 66,
    type: "지원사업",
    category: "global",
    period: "2024.05.01~2024.12.17",
    agency: "중소벤처기업부",
    title: "글로벌 기업 협업 프로그램 (ChatGPT 기반 건물 전력사용량 예측 및 ESS 최적 제어 솔루션",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 67,
    type: "PoC",
    category: "global",
    period: "2024.05.01~2024.11.30",
    agency: "중소벤처기업부",
    title: "2024년 해외실증(PoC) 지원 프로그램 창업기업",
    operatingOrganization: "창업진흥원",
  },
  {
    id: 68,
    type: "지원사업",
    category: "etc",
    period: "2024.11.22~2025.04",
    agency: "한국전력거래소",
    title: "2024년 한국전력거래소 창업ㆍ벤처기업 지원사업(선착순, 10개사)",
    operatingOrganization: "한국전력거래소",
  },
  {
    id: 69,
    type: "지원사업",
    category: "etc",
    period: "2024.11.22~2025.02.28",
    agency: "한국전력거래소",
    title: "2024년 한국토지주택공사 상생형 창업·벤처기업 지원사업",
    operatingOrganization: "한국전력거래소",
  },
  {
    id: 70,
    type: "사업화",
    category: "energy_business",
    period: "2024.05.27~2024.12.31",
    agency: "한국에너지공단",
    title: "AI기반 ESS 수요자원 관리 플랫폼 구축(미래 지역에너지 생태계 활성화 사업)",
    operatingOrganization: "한국에너지공단",
  },
  {
    id: 71,
    type: "지원사업",
    category: "etc",
    period: "2025.03.01~2026.02.28",
    agency: "한국여성과학기술인육성재단",
    title: "2025년 1차 과학기술분야 R&D 대체인력 활용 지원사업",
    operatingOrganization: "한국여성과학기술인육성재단",
  },
  {
    id: 72,
    type: "지원사업",
    category: "global",
    period: "-",
    agency: "중소벤처기업부",
    title: "2025년 그린벤처 유망기업 등 글로벌 진출지원 프로그램(상반기) 제1차 참가기업 모집",
    operatingOrganization: "-",
  },
  {
    id: 73,
    type: "지원사업",
    category: "etc",
    period: "2025.03.17~2025.12.31",
    agency: "경기창조경제혁신센터",
    title: "2025 기후테크 스타트업 육성사업",
    operatingOrganization: "경기창조경제혁신센터",
  },
  {
    id: 74,
    type: "용역",
    category: "etc",
    period: "2025.03.31~2025.08.31",
    agency: "LS 일렉트릭",
    title: "(SEI) Beyond X Enable 고도화 목적의 데이터 정제/가공 IT 용역 계약 건",
    operatingOrganization: "LS 일렉트릭",
  },
];

export const NINEWATT_PERFORMANCE_LIST_ENG: PerformanceDataType[] = [
  {
    id: 1,
    type: "R&D",
    category: "efficiency_diagnosis",
    period: "2019.07.01~2021.06.30",
    agency: "Korea Technology and Information Promotion Agency for SMEs",
    title:
      "TIPS, Private Investment-Led Technology Startup Support (Big Data Analysis-Based Building Energy Saving AI Platform)",
    operatingOrganization: "BluepointPartners",
  },
  {
    id: 2,
    type: "R&D",
    category: "efficiency_diagnosis",
    period: "-",
    agency: "Korea Electrical Manufacturers Association",
    title:
      "Corporate Autonomy Win-Win Program for Nurturing Companies: Korea Electric Power Corporation Energy Startup Program - Energy-saving AI platform through analysis of energy consumption patterns and energy-saving education",
    operatingOrganization: "Korea Electrical Manufacturers Association",
  },
  {
    id: 3,
    type: "Commercialization",
    category: "global",
    period: "2019.10.07~2019.12.31",
    agency: "ITP(Incheon Technopark)",
    title: "2019 Customized Global Support Project for SW Convergence",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 4,
    type: "Commercialization",
    category: "global",
    period: "2019.08.01~2020.07.31",
    agency: "Ministry of SMEs and Startups",
    title:
      "2019 TIPS Overseas Marketing Support Project Public-Private Joint Startup Founder Discovery and Nurturing Project",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 5,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2019.11.18~2020.09.18",
    agency: "Korea Social Investment Foundation",
    title:
      "2019 Korea Electric Power Corporation's Impact Investment in Social Economy Organizations in the Energy Sector: Development, Production, and Sales of Energy Consumption Pattern and Usage Analysis Device (Edge Computing Controller; ECC) and Solutions",
    operatingOrganization: "Korea Social Investment Foundation",
  },
  {
    id: 6,
    type: "Commercialization",
    category: "etc",
    period: "2019.11.11~2019.12.31",
    agency: "ITP(Incheon Technopark)",
    title: "SW Convergence Cluster 2.0 Data-Based Business Model Research Group Support Project",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 7,
    type: "Commercialization",
    category: "global",
    period: "2019.12.10~2020.06.30",
    agency: "ITP(Incheon Technopark)",
    title:
      "SW Convergence Cluster 2.0 Global Industry-Academia-Research Cooperation Project Development of devices considering the improvement of digital information accessibility for elderly living alone",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 8,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2020.04.13~2020.11.20",
    agency: "Korea Energy Agency",
    title: "Corporate Cooperation Energy Companion Project",
    operatingOrganization: "KEPCO(Korea Electric Power Corporation)",
  },
  {
    id: 9,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2020.05.01~2020.12.31",
    agency: "ITP(Incheon Technopark)",
    title:
      "SW Convergence Cluster 2.0 Project (SW Development for Preemptive Prevention of Loneliness Linked to Energy Voucher)",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 10,
    type: "Support Project",
    category: "etc",
    period: "2020.02.08~2020.12.31",
    agency: "Korea Social Enterprise Promotion Agency",
    title: "Social Entrepreneur Incubation Project",
    operatingOrganization: "SEempower",
  },
  {
    id: 11,
    type: "Support Project",
    category: "efficiency_diagnosis",
    period: "2020.04.13~2020.08.12",
    agency: "ITP(Incheon Technopark)",
    title:
      "2020 Research and Development Planning Consulting Support Project (Energy Voucher Linked Appropriate Energy Consumption Recommendation Service)",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 12,
    type: "Support Project",
    category: "etc",
    period: "2020.08.01~2021.04.30",
    agency: "Chairman of the Korea Electrical Manufacturers Association장",
    title:
      "Win-Win Supporters Program Incubation Company Standard Agreement (Corporate Autonomous Win-Win Program KEPCO KDN Energy ICT 4.0 Startup Incubation Project)",
    operatingOrganization: "Chairman of the Korea Electrical Manufacturers Association장",
  },
  {
    id: 13,
    type: "Support Project",
    category: "etc",
    period: "2020.10.05~2021.06.30",
    agency: "Chairman of the Korea Electrical Manufacturers Association장",
    title:
      "Corporate Autonomous Win-Win Program Incubation Company Standard Agreement(Corporate Autonomous Win-Win Program KEPCO Energy Startup Support Project)",
    operatingOrganization: "Chairman of the Korea Electrical Manufacturers Association장",
  },
  {
    id: 14,
    type: "R&D",
    category: "urban_carbon",
    period: "2021.01.01~2023.12.31",
    agency: "Ministry of Science and ICT",
    title:
      "Creation of AI-Centered Industrial Convergence Complex (R&D) (Development of an Energy Disaster Response Platform Capable of Preventive Measures and Rapid Recovery Based on AI)",
    operatingOrganization: "Seoul National University R&DB Foundation",
  },
  {
    id: 15,
    type: "R&D",
    category: "energy_business",
    period: "2021.04.01~2025.12.31",
    agency: "KETEP(Korea Institute of Energy Technology Evaluation and Planning)",
    title: "Wind Energy Cluster Talent Development Project in Gyeongbuk Region (R&D)",
    operatingOrganization: "Gyeongbuk Technopark",
  },
  {
    id: 16,
    type: "R&D",
    category: "urban_carbon",
    period: "2021.05.01~2021.12.31",
    agency: "Ministry of Science and ICT",
    title: "2021 Core Industry Cloud Flagship Project Support Task",
    operatingOrganization: "National IT Industry Promotion Agency",
  },
  {
    id: 17,
    type: "Service",
    category: "zero_energy",
    period: "2021.10.06~2021.12.15",
    agency: "KICT-KOREA INSTITUTE of CIVIL ENGINEERING and BUILDING TECHNOLOGY",
    title:
      "Public Building Energy Consumption Disclosure and Performance Improvement Project Technical Support Service",
    operatingOrganization: "KICT-KOREA INSTITUTE of CIVIL ENGINEERING and BUILDING TECHNOLOGY",
  },
  {
    id: 18,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2021.04.26~2021.11.19",
    agency: "Korea Energy Agency",
    title: "Corporate Cooperation Energy Partnership Project",
    operatingOrganization: "KEPCO(Korea Electric Power Corporation)",
  },
  {
    id: 19,
    type: "Commercialization",
    category: "etc",
    period: "2021.06.01~2021.10.31",
    agency: "Korea Data Agency",
    title:
      "2021 DATA-SATARS (Data Utilization Business Support) Project Energy Investment-Linked AI Platform",
    operatingOrganization: "Korea Data Agency",
  },
  {
    id: 20,
    type: "Support Project",
    category: "etc",
    period: "2021.02.01~2021.04.30",
    agency: "Work Together Foundation",
    title:
      "Korea District Heating Corporation's Eco-Friendly Corporate Autonomy Support Project 'The Minimize'",
    operatingOrganization: "Work Together Foundation",
  },
  {
    id: 21,
    type: "Support Project",
    category: "etc",
    period: "2021.04.15~2021.12.31",
    agency: "KEPCO Knowledge, Data & Network Co., Ltd.",
    title: "KDN's Social Economy Support Management Improvement Project",
    operatingOrganization: "Social Solidarity Bank",
  },
  {
    id: 22,
    type: "Support Project",
    category: "etc",
    period: "2021.05.10~2021.08.13",
    agency: "MYSC",
    title: "H-On Dream Startup Ground",
    operatingOrganization: "MYSC",
  },
  {
    id: 23,
    type: "Support Project",
    category: "etc",
    period: "2021.06.01~2021.11.30",
    agency: "ITP(Incheon Technopark)",
    title:
      "SW Convergence Cluster 2.0 Project SaaS-Based Water Consumption Data Management Service",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 24,
    type: "Support Project",
    category: "etc",
    period: "2021.09.23~2022.04.30",
    agency: "Korea Electrical Manufacturers Association",
    title: "Corporate Autonomy Win-Win Program Nurturing Companies 2021 KDN-STARS Companies",
    operatingOrganization: "Korea Electrical Manufacturers Association",
  },
  {
    id: 25,
    type: "R&D",
    category: "urban_carbon",
    period: "2022.04.01~2025.03.31",
    agency: "Ministry of SMEs and Startups",
    title:
      "Green Remodeling Matching Service that Integrates Urban Carbon Reduction and Green Finance",
    operatingOrganization: "Ministry of SMEs and Startups",
  },
  {
    id: 26,
    type: "R&D",
    category: "urban_carbon",
    period: "2022.04.15~2024.12.31",
    agency: "Korea Agency for Infrastructure Technology Advancement",
    title: "Digital Diagnosis Modular Technology for Improving Green Remodeling Efficiency",
    operatingOrganization: "Korea Agency for Infrastructure Technology Advancement",
  },
  {
    id: 27,
    type: "Commercialization",
    category: "urban_carbon",
    period: "2022.04.01~2025.03.31",
    agency: "Ministry of SMEs and Startups",
    title: "Green Venture Program Commercialization",
    operatingOrganization: "Ministry of SMEs and Startups",
  },
  {
    id: 28,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2022.04.29~2022.11.30",
    agency: "Korea Energy Agency",
    title: "2022 Corporate Cooperation Energy Companion Project",
    operatingOrganization: "KEPCO(Korea Electric Power Corporation)",
  },
  {
    id: 29,
    type: "Commercialization",
    category: "etc",
    period: "2022.12.15~2023.05.31",
    agency: "Ministry of SMEs and Startups",
    title: "Big-Star Problem Solver Platform for the 4th Industrial Revolution",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 30,
    type: "Commercialization",
    category: "etc",
    period: "2022.11.01~2022.12.31",
    agency: "ITP(Incheon Technopark)",
    title: "Incheon SOS Lab Platform-Based Project Execution Companies",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 31,
    type: "Business Support",
    category: "etc",
    period: "2022.02.25~2022.11.30",
    agency: "Land and Geospatial Informatix Corporation",
    title:
      "Corporate Autonomy Win-Win Program Support Agreement 6th Spatial Information Utilization Startup Idea Contest Commercialization Support",
    operatingOrganization:
      "Korea Foundation for Cooperation of Large & Small Business, Rural Affairs",
  },
  {
    id: 32,
    type: "Business Support",
    category: "etc",
    period: "2022.05.01~2023.01.31",
    agency: "Ministry of SMEs and Startups",
    title: "Non-Face-to-Face Startup Nurturing Project for Startup Companies",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 33,
    type: "Business Support",
    category: "etc",
    period: "2022.06.01~2022.11.30",
    agency: "Korea Data Agency",
    title: "2022 Data Voucher Support Project",
    operatingOrganization: "Korea Data Agency",
  },
  {
    id: 34,
    type: "Business Support",
    category: "etc",
    period: "2022.06.03~2022.12.15",
    agency: "National Information Society Agency",
    title: "2022 Public Data Company Matching Support Project",
    operatingOrganization: "National Information Society Agency",
  },
  {
    id: 35,
    type: "Business Support",
    category: "etc",
    period: "2022.09.06~2023.02.28",
    agency: "Seoul Business Agency, SBA",
    title:
      "Seoul Startup Hub Large Company Cooperation Program Large Company LS Electric Cooperation Program",
    operatingOrganization: "Seoul Business Agency, SBA",
  },
  {
    id: 36,
    type: "Business Support",
    category: "urban_carbon",
    period: "2022.12.01~2023.05.31",
    agency: "KOREA INNOVATION FOUNDATION",
    title: "2022 Incheon Seo-gu Small Business Special Growth Package",
    operatingOrganization: "KOREA INNOVATION FOUNDATION",
  },
  {
    id: 37,
    type: "Business Support",
    category: "etc",
    period: "2022.12.26~2023.05.31",
    agency: "Korea Western Power Co., Ltd.",
    title: "Korea Western Power Co., Ltd. Win-Win Startup-Venture Business Support Project",
    operatingOrganization: "Korea Western Power Co., Ltd.",
  },
  {
    id: 38,
    type: "Business Support",
    category: "etc",
    period: "2022.12.20~2023.04.30",
    agency: "Social Solidarity Bank",
    title:
      "2022 Korea District Heating Corporation Win-Win Startup-Venture Business Support Project",
    operatingOrganization: "Social Solidarity Bank",
  },
  {
    id: 39,
    type: "PoC",
    category: "global",
    period: "2022.10.26~2023.02.28",
    agency: "Seoul Business Agency, SBA",
    title: "SBA-KITA UK Smart City PoC",
    operatingOrganization: "Seoul Business Agency, SBA",
  },
  {
    id: 40,
    type: "R&D",
    category: "urban_carbon",
    period: "2023.04.01~2026.12.31",
    agency: "Ministry of Land, Infrastructure and Transport",
    title: "Establishment of Integrated Management Foundation for Building Energy Consumption Data",
    operatingOrganization: "KICT-KOREA INSTITUTE of CIVIL ENGINEERING and BUILDING TECHNOLOGY",
  },
  {
    id: 41,
    type: "R&D",
    category: "smart_city",
    period: "2023.12.10~2026.12.09",
    agency: "Ministry of SMEs and Startups",
    title: "Scale-up TIPS Investment Linkage",
    operatingOrganization: "ninewatt",
  },
  {
    id: 42,
    type: "Service",
    category: "efficiency_diagnosis",
    period: "2023.04.18~2023.08.30",
    agency: "LS ELECTRIC",
    title: "Smart Diagnosis MVP 3.0 Energy Reporting Service Enhancement Project",
    operatingOrganization: "LS ELECTRIC",
  },
  {
    id: 43,
    type: "Service",
    category: "etc",
    period: "2023.04.19~2023.12.13",
    agency: "KEPCO(Korea Electric Power Corporation)",
    title: "Development of Digital Construction Cost Information Algorithm",
    operatingOrganization: "KEPCO(Korea Electric Power Corporation)",
  },
  {
    id: 44,
    type: "Service",
    category: "efficiency_diagnosis",
    period: "2023.12.01~2024.01.31",
    agency: "SQISOFT Inc.",
    title: "2023 Public Building Energy Consumption Data Verification and Analysis",
    operatingOrganization: "SQISOFT Inc.",
  },
  {
    id: 45,
    type: "Commercialization",
    category: "efficiency_diagnosis",
    period: "2023.05.18~2025.12.31",
    agency: "Korea Authority of Land & Infrastructure Safety",
    title: "2023 Comprehensive Support for Green Remodeling of Public Buildings",
    operatingOrganization: "Korea Authority of Land & Infrastructure Safety",
  },
  {
    id: 46,
    type: "Business Support",
    category: "etc",
    period: "2023.01.01~2023.12.31",
    agency: "-",
    title: "2023 Corporate Advertising Support Project",
    operatingOrganization: "-",
  },
  {
    id: 47,
    type: "Business Support",
    category: "smart_city",
    period: "2023.03.23~2023.11.30",
    agency: "ITP(Incheon Technopark)",
    title: "2023 Demonstration Commercialization Program",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 48,
    type: "Business Support",
    category: "etc",
    period: "2023.05.09~2023.08.11",
    agency: "ITP(Incheon Technopark)",
    title: "2023 First IP Narae Program",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 49,
    type: "Business Support",
    category: "zero_energy",
    period: "2023.04.20~2023.11.30",
    agency: "Inchon Intellectual Property Center",
    title: "[Incheon Startup Park] Smart-X City (Incheon Urban Corporation)",
    operatingOrganization: "Inchon Intellectual Property Center",
  },
  {
    id: 50,
    type: "Business Support",
    category: "global",
    period: "2023.04.20~2023.11.24",
    agency: "ITP(Incheon Technopark)",
    title: "[Incheon Startup Park] Scale-Up Challenge Lab",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 51,
    type: "Business Support",
    category: "efficiency_diagnosis",
    period: "2023.05.01~2024.02.29",
    agency: "ITP(Incheon Technopark)",
    title: "2023 Startup Leap Package Support Project (Urban Energy Efficiency Solutions)",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 52,
    type: "Business Support",
    category: "urban_carbon",
    period: "2023.07.06~2023.12.31",
    agency: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
    title: "Gangnam District Office Demonstration Support Project",
    operatingOrganization: "-",
  },
  {
    id: 53,
    type: "Business Support",
    category: "etc",
    period: "2023.07.31~2023.11.30",
    agency: "ITP(Incheon Technopark)",
    title: "2023 Artificial Intelligence (AI) Business Model Research Group",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 54,
    type: "Business Support",
    category: "zero_energy",
    period: "2023.08.07~2023.11.30",
    agency: "ITP(Incheon Technopark)",
    title: "Incheon Startup Park Smart-X Energy [LS Electric] Program",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 55,
    type: "Business Support",
    category: "etc",
    period: "2023.09.01~2023.11.30",
    agency: "ITP(Incheon Technopark)",
    title:
      "Win-Win Startup-Venture Company Support Project (KEPCO Startup Open Innovation Support Project)",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 56,
    type: "Business Support",
    category: "etc",
    period: "2023.09.01~2023.11.15",
    agency: "KEPCO(Korea Electric Power Corporation)",
    title: "Inter-Regional Business Model Demonstration Support Project",
    operatingOrganization: "KEPCO(Korea Electric Power Corporation)",
  },
  {
    id: 57,
    type: "Business Support",
    category: "global",
    period: "2023.09.18~2023.11.30",
    agency: "ITP(Incheon Technopark)",
    title:
      "Win-Win Startup-Venture Company Support Project (2023 Energy ICT Sector Startup-Venture Company Overseas Market Development Support Project (Overseas Certification Project))",
    operatingOrganization: "ITP(Incheon Technopark)",
  },
  {
    id: 58,
    type: "Business Support",
    category: "global",
    period: "2023.09.18~2023.11.30",
    agency: "KEPCO Knowledge, Data & Network Co., Ltd.",
    title:
      "Win-Win Startup-Venture Company Support Project (2023 Energy ICT Sector Startup-Venture Company Overseas Market Development Support Project (Overseas Market Research))",
    operatingOrganization: "KEPCO Knowledge, Data & Network Co., Ltd.",
  },
  {
    id: 59,
    type: "PoC",
    category: "smart_city",
    period: "2023.11.01~2024.07.31",
    agency: "KEPCO Knowledge, Data & Network Co., Ltd.",
    title:
      "Development and Visualization of Algorithms and Simulations for Energy Efficiency Management of Future Mobility Hubs",
    operatingOrganization: "KEPCO Knowledge, Data & Network Co., Ltd.",
  },
  {
    id: 60,
    type: "Business Support",
    category: "etc",
    period: "-",
    agency: "HYUNDAI NGV",
    title:
      "2023 Second Round Technology Development Product Public Institution Demonstration Support Project",
    operatingOrganization: "HYUNDAI NGV",
  },
  {
    id: 61,
    type: "PoC",
    category: "global",
    period: "2023.06.01~2023.11.30",
    agency: "Ministry of SMEs and Startups",
    title: "(KSC) Data-Based Building Energy Performance Diagnosis and Green Remodeling Solutions",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 62,
    type: "PoC",
    category: "global",
    period: "2023.12.08~2024.12.13",
    agency: "Seoul Digital Foundation",
    title: "Seoul Smart City Solution Overseas (London) Demonstration Support Project",
    operatingOrganization: "Seoul Digital Foundation",
  },
  {
    id: 63,
    type: "R&D",
    category: "urban_carbon",
    period: "2024.07.01~2027.04",
    agency: "Korea Agency for Infrastructure Technology Advancement",
    title:
      "Cooperative Hub-type National Land and Transportation International Cooperation Research and Development Project (Development of AI Assistant Building Energy Analysis Technology and Platform for Innovative Transition to Net Zero in Urban Buildings)",
    operatingOrganization: "KICT-KOREA INSTITUTE of CIVIL ENGINEERING and BUILDING TECHNOLOGY",
  },
  {
    id: 64,
    type: "Support Project",
    category: "etc",
    period: "2024.03.29~2024.12.31",
    agency: "TAP ANGEL PARTNERS",
    title: "2024 Agricultural and Food Technology Startup Accelerating Agreement",
    operatingOrganization: "TAP ANGEL PARTNERS",
  },
  {
    id: 65,
    type: "Support Project",
    category: "global",
    period: "2024.07.24~2024.11.29",
    agency: "KEPCO Knowledge, Data & Network Co., Ltd.",
    title:
      "2024 Energy ICT Sector Startup-Venture Company Overseas Market Development Support Project",
    operatingOrganization: "KEPCO Knowledge, Data & Network Co., Ltd.",
  },
  {
    id: 66,
    type: "Support Project",
    category: "global",
    period: "2024.05.01~2024.12.17",
    agency: "Ministry of SMEs and Startups",
    title:
      "Global Corporate Collaboration Program (ChatGPT-based Building Power Consumption Prediction and ESS Optimal Control Solution)",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 67,
    type: "PoC",
    category: "global",
    period: "2024.05.01~2024.11.30",
    agency: "Ministry of SMEs and Startups",
    title: "2024 Overseas Demonstration (PoC) Support Program for Startups",
    operatingOrganization: "KISED(Korea Institute of Startup and Entrepreneurship Development)",
  },
  {
    id: 68,
    type: "Support Project",
    category: "etc",
    period: "2024.11.22~2025.04",
    agency: "Korea Power Exchange",
    title:
      "2024 Korea Power Exchange Startup and Venture Company Support Project (First come, first served, 10 companies)",
    operatingOrganization: "Korea Power Exchange",
  },
  {
    id: 69,
    type: "Support Project",
    category: "etc",
    period: "2024.11.22~2025.02.28",
    agency: "Korea Power Exchange",
    title:
      "2024 Korea Land and Housing Corporation Win-Win Startup and Venture Company Support Project",
    operatingOrganization: "Korea Power Exchange",
  },
  {
    id: 70,
    type: "Commercialization",
    category: "energy_business",
    period: "2024.05.27~2024.12.31",
    agency: "Korea Energy Agency",
    title:
      "Establishment of AI-based ESS Demand Resource Management Platform (Future Local Energy Ecosystem Activation Project)",
    operatingOrganization: "Korea Energy Agency",
  },
  {
    id: 71,
    type: "Support Project",
    category: "etc",
    period: "2025.03.01~2026.02.28",
    agency: "Korea Foundation for Women In Science, Engineering and Tech, WISET",
    title:
      "2025 First Science and Technology Sector R&D Alternative Workforce Utilization Support Project",
    operatingOrganization: "Korea Foundation for Women In Science, Engineering and Tech, WISET",
  },
  {
    id: 72,
    type: "Support Project",
    category: "global",
    period: "-",
    agency: "Ministry of SMEs and Startups",
    title:
      "2025 Green Venture Promising Companies Global Expansion Support Program (First Half) First Participant Recruitment",
    operatingOrganization: "-",
  },
  {
    id: 73,
    type: "Support Project",
    category: "etc",
    period: "2025.03.17~2025.12.31",
    agency: "Gyeonggi Center for Creative Economy & Innovation",
    title: "2025 Climate Tech Startup Incubation Project",
    operatingOrganization: "Gyeonggi Center for Creative Economy & Innovation",
  },
  {
    id: 74,
    type: "Service",
    category: "etc",
    period: "2025.03.31~2025.08.31",
    agency: "LS ELECTRIC",
    title:
      "(SEI) Data refinement/processing IT Service contract for the purpose of enhancing Beyond X Enable.",
    operatingOrganization: "LS ELECTRIC",
  },
];
